apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-rag   # Changed from rag-skeleton
  labels:
    app: eks-rag  # Changed to match
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-rag  # Changed to match
  template:
    metadata:
      labels:
        app: eks-rag  # Changed to match
    spec:
      containers:
      - name: eks-rag  # Changed from rag-skeleton
        image: advanced-rag-mloeks/eks-rag:latest
        imagePullPolicy: Never  # This is important for using local images
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
